### ISSUE TITLE
hypeerbolic._2 point.euclidiandistance possui um erro

### ISSUE THREAD

**Issue by cyromd** [Metria-Project/Metria#2]
branch rewrite
error has been ocorred in line 79
where is wrotten "return Math.Sqrt(Math.Pow(this.X - P.X, 2) + Math.Pow(this.X - P.X, 2));"
should be wrotten "return Math.Sqrt(Math.Pow(this.X - P.X, 2) + Math.Pow(this.Y - P.Y, 2));"

**Comment by Supitto** [comment]
Okay, doing that on branch "Issue2"

**Comment by Supitto** [comment]
Done, updated and merged to master since theres no test to be done
