### ISSUE TITLE
DUVIDA no codigo de IntersectionPoint em LineSegement

### ISSUE THREAD

**Issue by cyromd** [Metria-Project/Metria#25]
nesse método pode acontecer do segmento pode coincidir com parte da reta, isso daria mais de um ponto na intercessão e pelo o que eu entendi no código não tem nada tratando esse caso ou excluindo a possibilidade dele acontecer

**Comment by Supitto** [comment]
In fact, it will throw a error when the base class intersctionpoint method is called. Look at Line IntersectionPoint and you will see
