### ISSUE TITLE
DUVIDA  no codigo de RAY

### ISSUE THREAD

**Issue by cyromd** [Metria-Project/Metria#26]
Se ray é uma semireta então ela começa em um ponto e, seguindo um unico sentido, vai ate o infinito. Mas no código de Ray não tem nada especificando qual dos pontos _a ou _b vai ser o "ponto inicial" da reta e pra qual dos lados ela vai se estender até o infinito.

**Comment by Supitto** [comment]
In fact, ray begins a P passing through Q
