### ISSUE TITLE
hyperbolic._2 point.euclipowereddiandistance possui um erro

### ISSUE THREAD

**Issue by cyromd** [Metria-Project/Metria#3]
branch rewrite
error has been ocorred in line 91
where is wrotten "return Math.Pow(this.X - P.X, 2) + Math.Pow(this.X - P.X, 2);"
should be wrotten "return Math.Pow(this.X - P.X, 2) + Math.Pow(this.Y - P.Y, 2);"

**Comment by Supitto** [comment]
Already fixed on issue #2
