### ISSUE TITLE
rewrite Metria/Hyperbolic/_2/Line/FixValues (SOBRE OS ERROS NOS TESTES)

### ISSUE THREAD

**Issue by cyromd** [Metria-Project/Metria#55]
Cara é sobre o erro nos testes, na linha 101 onde é calculado o center das retas tortas, pega a visão...
no código você cria uma line euclidiana, ou seja uma reta normal, que passa pelo ponto A e pelo ponto B e intersecta ela com uma outra reta euclidiana que passa pelo ponto (0,0) e (1,0), ou seja o eixo x. Mas na maioria dos inputs dos testes os pontos, a partir dos quais as lines são construídas, possuem as respectivas coordenadas em x diferentes e as respectivas coordenadas em y iguais, logo são retas paralelas ao eixo x. (Acho que aqui já deu pra entender onde eu quero chegar.)
Então um dos erros com certeza está nesse caso, pois o center é calculado através da intersecção de duas retas, porém nesse caso específico, no qual muitos testes fazem parte, o resultado está vindo de uma suposta intersecção de duas retas paralelas, logo pode estar sendo atribuído qualquer valor absurdo para o center das retas tortas, inclusive null. 
(O que está sendo discutido nesse primeiro parágrafo com certeza está certo e temos que achar uma resolução para esses casos.)
(No parágrafo abaixo colocarei uma dúvida minha que eu creio que pode ser fonte de erro.)
Na segunda reta criada na linha 101 é usado point() que deve ser a origem (0,0), mas não tem a possibilidade de ser o 'null'? Se for isso pode estar sendo uma das fontes de erro

**Comment by Supitto** [comment]
Perfeito, apliquei a mudança e os testes subiram de 29 para 44 em corretude. Ainda existem alguns testes acusando null exception. Mas preciso terminar de revisalos para ter certeza se é a metria ou se há algum erro no teste

**Comment by Supitto** [comment]
As mudanças já vieram  no ultimo commit
