### ISSUE TITLE
Error in code text hyperbolic.2 Line  

### ISSUE THREAD

**Issue by cyromd** [Metria-Project/Metria#6]
branch rewrite
the "_center" , line 101, have a error i=in the equation, is missiing the equation of perpendicular line

**Comment by Supitto** [comment]
Ok, seems fair. I'm going to redo this part of the code, but need you to do a code check once it is done.
The code will be on branch Issue6

**Comment by Supitto** [comment]
It is already pushed to origin, so once the code check is done i'll close the issue. thanks for the issue
